export const adminTheme = {
  colors: {
    background: "#fbf9f8",
    surface: "#ffffff",
    surfaceLow: "#f6f3f2",
    surfaceContainer: "#f0eded",
    surfaceVariant: "#e4e2e1",
    outline: "#8f7069",
    outlineVariant: "#e3beb6",
    onSurface: "#1b1c1c",
    onSurfaceVariant: "#5b403b",
    primary: "#b22204",
    primaryContainer: "#d63c1e",
    onPrimary: "#ffffff",
    onPrimaryContainer: "#fffbff",
    secondary: "#5d5f5f",
    secondaryContainer: "#dfe0e0",
    onSecondaryContainer: "#616363",
    accent: "#EE4D2D",
    success: "#1f9d55",
    danger: "#ba1a1a",
    warning: "#b25a00",
    muted: "#7d6f6c",
    subtleText: "#8a7b77",
    inputBg: "#f9f6f5",
  },
  radius: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    pill: 999,
  },
  shadow: {
    card: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    lift: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
  },
  glassCard: {
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(232,232,232,0.5)",
  },
};
