export const adminTheme = {
  colors: {
    background: "#FAFAFA",
    surface: "#FFFFFF",
    surfaceLow: "#F5F5F5",
    surfaceContainer: "#F0F0F0",
    surfaceVariant: "#EBEBEB",
    outline: "#9CA3AF",
    outlineVariant: "#E5E7EB",
    onSurface: "#1A1A1A",
    onSurfaceVariant: "#6B7280",
    primary: "#FF6B35",
    primaryContainer: "#FFD700",
    onPrimary: "#FFFFFF",
    onPrimaryContainer: "#FFFFFF",
    secondary: "#6B7280",
    secondaryContainer: "#E5E7EB",
    onSecondaryContainer: "#1F2937",
    accent: "#FF8C42",
    success: "#22C55E",
    danger: "#EF4444",
    onDanger: "#FFFFFF",
    warning: "#F59E0B",
    muted: "#9CA3AF",
    subtleText: "#9CA3AF",
    inputBg: "#F3F4F6",
  },
  radius: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    pill: 999,
  },
  shadow: {
    card: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    lift: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 12,
      elevation: 5,
    },
  },
  glassCard: {
    backgroundColor: "rgba(255,255,255,0.9)",
    borderWidth: 1,
    borderColor: "rgba(232,232,232,0.5)",
  },
};
